version: '3.8'

services:
  redis:
    image: 'redis:7.0'
    ports:
      - ${IMAGE_API_REDIS_PORT}:${IMAGE_API_REDIS_PORT}
  image-api-server:
    restart: on-failure
    build:
      dockerfile: ./server/Dockerfile
      context: .
    hostname: image-api
    ports:
      - ${IMAGE_API_PORT}:${IMAGE_API_PORT}
    environment:
      - REDIS_HOST=redis
      - IMAGE_API_KEY=${IMAGE_API_KEY}
      - IMAGE_API_PORT=${IMAGE_API_PORT}
      - IMAGE_API_REDIS_PORT=${IMAGE_API_REDIS_PORT}
