name: Environment Setup
description: 'Setup PNPM and Node'
runs:
  using: 'composite'
  steps:
    - name: Set up NodeJS v16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.32.4
        run_install: true
