name: PR Commit
on:
  pull_request:
    branches: [main]
env:
  WORKSPACE_ROOT: .

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - name: Lint source code
        run: pnpm run lint

  check-format:
    name: Check Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - name: Check code format
        run: pnpm run format:check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: pnpm run test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - uses: ./.github/actions/build
      - name: Run server
        run: pnpm run start &
      - name: Wait server start
        run: sleep 20
      - name: Run integration tests
        run: pnpm run integration

  build-server:
    name: Build server
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/env-setup
      - name: Build server
        run: pnpm run build

  # build-web:
  #   name: Build client library
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout code into workspace directory
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/env-setup
  #     - name: Build web
  #       run: pnpm run build:web

  # build-wasm:
  #   name: Build wasm libraries
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout code into workspace directory
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: ./.github/actions/env-setup
  #     - name: Install wasm-pack
  #       run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  #     - name: Build image-rs
  #       run: pnpm run build:image-rs
